<%
IF langCode = "eng" Then
	LangPack_sitemAll = "All"
	LangPack_sitemTitle = "Title"
	LangPack_sitemName = "Name"
	LangPack_sitemCon = "Content"
	LangPack_sStrPlaceHolder = "Please enter your search term"
	LangPack_sBtn = "Search"

	LangPack_lWriteBtn = "Write"
	LangPack_lNo = "No"
	LangPack_lCate = "Category"
	LangPack_lTitle = "Title"
	LangPack_lWriter = "Name"
	LangPack_lDate = "Date"
	LangPack_lHit = "Hit"
	LangPack_lDateTerm = "Period"
	LangPack_lStatus = "State"
	LangPack_lDown = "Down"
	
	LangPack_wCompany = "Company"
	LangPack_wWriter = "Name"
	LangPack_wSecret = "Secret"
	LangPack_wCate = "Category"
	LangPack_wStar = "Grade"
	LangPack_wTel = "Phone"
	LangPack_wEmail = "Email"
	LangPack_wTitle = "Title"
	LangPack_wCon = "Content"
	LangPack_wPass = "Password"
	LangPack_wImage = "Image"
	LangPack_wFiles = "File upload"
	LangPack_wRequired = "is a required field."
	LangPack_wProductNm = "Product"
	LangPack_wApplication = "Application"

	LangPack_wDate = "Date"
	LangPack_wHit = "Hit"
	LangPack_wReplyWaiting = "Waiting"
	LangPack_wReplyCom = "Complete"
	LangPack_wPrev = "Prev"
	LangPack_wNext = "Next"

	LangPack_FileAddBtn = "Add"
	LangPack_FileDownBtn = "Down"
	LangPack_FileDelChk = "Remove"
	LangPack_FileSearch = "Find"

	LangPack_SelboxBSort = "Select"
	LangPack_SelboxTel = "Select"
	LangPack_SelboxEdomain = "Direct input"

	LangPack_wBtnContact = "Contact"
	LangPack_wBtnApply = "Apply"
	LangPack_wBtnSubmit = "Submit"
	LangPack_wBtnModify = "Modified"
	LangPack_wBtnDel = "Remove"
	LangPack_wBtnList = "List"
	LangPack_wBtnCancel = "Cancel"

	LangPack_PolicyTitle = "Personal Information Processing Policy"
	LangPack_PolicyTxt = "I agree to the privacy policy."

	Langpack_EnterPassMsg = "Enter a password."
	Langpack_RemoveComMsg = "This post has been removed."
	Langpack_AuthErrorMsg = "About the author does not match."
	Langpack_AuthErrorMsg_Modify = "Only the author himself can edit."
	Langpack_AuthErrorMsg_View = "Only the author himself can view."
	Langpack_PassErrorMsg = "Passwords do not match."
	LangPack_PostDeletedMsg = "The post has been deleted."
	LangPack_PostNotFoundMsg = "No Posts Found."
	Langpack_WriteOkMsg = "Your post has been uploaded."
	Langpack_ModifyOkMsg = "Your post has been edited."
	Langpack_inquiryOkMsg = "Your inquiry has been received."
	LangPack_FileAllowLimit30mMsg = "Beyond the accepted upload capacity (30M) failed to upload."
	Langpack_WrongMsg = "The wrong approach."
	Langpack_PrevNotFound = "No previous article."
	Langpack_NextNotFound = "No next article."

	LangPack_Reply = "Reply"
	LangPack_Notice = "Notice"
	LangPack_Expected = "Expected"
	LangPack_Progress = "Progress"
	LangPack_Deadline = "Deadline"
Else
	LangPack_sitemAll = "전체"
	LangPack_sitemTitle = "제목"
	LangPack_sitemName = "작성자"
	LangPack_sitemCon = "내용"
	LangPack_sStrPlaceHolder = "검색어를 입력 하세요"
	LangPack_sBtn = "검색"

	LangPack_lWriteBtn = "작성하기"
	LangPack_lNo = "No"
	LangPack_lCate = "구분"
	LangPack_lTitle = "제목"
	LangPack_lWriter = "작성자"
	LangPack_lDate = "등록일"
	LangPack_lHit = "조회수"
	LangPack_lDateTerm = "공고기간"
	LangPack_lStatus = "상태"
	LangPack_lDown = "파일"

	LangPack_wCompany = "회사명"
	LangPack_wWriter = "이름"
	LangPack_wSecret = "비밀글"
	LangPack_wCate = "구분"
	LangPack_wStar = "평점"
	LangPack_wTel = "연락처"
	LangPack_wEmail = "이메일"
	LangPack_wTitle = "제목"
	LangPack_wCon = "내용"
	LangPack_wPass = "비밀번호"
	LangPack_wImage = "대표이미지"
	LangPack_wFiles = "파일첨부"
	LangPack_wRequired = "표시는 필수 입력 항목입니다."
	LangPack_wProductNm = "제품명"
	LangPack_wApplication = "어플리케이션"

	LangPack_wDate = "등록일"
	LangPack_wHit = "조회수"
	LangPack_wReplyWaiting = "답변대기"
	LangPack_wReplyCom = "답변완료"
	LangPack_wPrev = "이전글"
	LangPack_wNext = "다음글"

	LangPack_FileAddBtn = "파일추가"
	LangPack_FileDownBtn = "다운로드"
	LangPack_FileDelChk = "삭제"
	LangPack_FileSearch = "파일찾기"

	LangPack_SelboxBSort = "선택"
	LangPack_SelboxTel = "선택"
	LangPack_SelboxEdomain = "직접입력"

	LangPack_wBtnContact = "문의하기"
	LangPack_wBtnApply = "신청하기"
	LangPack_wBtnSubmit = "확인"
	LangPack_wBtnModify = "수정"
	LangPack_wBtnDel = "삭제"
	LangPack_wBtnList = "목록"
	LangPack_wBtnCancel = "취소"

	LangPack_PolicyTitle = "개인정보 보호 이용자 동의서"
	LangPack_PolicyTxt = "개인정보처리방침 및 이용안내에 동의합니다.(필수)"

	Langpack_EnterPassMsg = "비밀번호를 입력해주세요."
	Langpack_RemoveComMsg = "게시물이 삭제되었습니다."
	Langpack_AuthErrorMsg = "작성자 정보와 일치하지 않습니다."
	Langpack_AuthErrorMsg_Modify = "작성자 본인만 수정가능합니다."
	Langpack_AuthErrorMsg_View = "작성자 본인만 확인가능합니다."
	Langpack_PassErrorMsg = "비밀번호가 일치하지 않습니다."
	LangPack_PostDeletedMsg = "삭제된 게시물입니다."
	LangPack_PostNotFoundMsg = "검색된 게시물이 없습니다."
	Langpack_WriteOkMsg = "게시물이 등록 되었습니다."
	Langpack_ModifyOkMsg = "게시물이 수정 되었습니다."
	Langpack_inquiryOkMsg = "접수 되었습니다."
	LangPack_FileAllowLimit30mMsg = "업로드 허용용량(30M)을 초과하여 업로드를 실패하였습니다."
	Langpack_WrongMsg = "잘못된 접근입니다."
	Langpack_PrevNotFound = "이전글이 없습니다."
	Langpack_NextNotFound = "다음글이 없습니다."

	LangPack_Reply = "답변"
	LangPack_Notice = "공지"
	LangPack_Expected = "예정"
	LangPack_Progress = "진행"
	LangPack_Deadline = "마감"
End IF
%>